server:
    port: 9000
spring:
  application:
    name: web-based-erp
  datasource:
      name: erp-db
      url: jdbc:mysql://120.78.91.69:3306/db_erp?useSSL=false&useUnicode=true&characterEncoding=utf8
      username: root
      password: passw0rd
      driver-class-name: com.mysql.jdbc.Driver

  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
    multipart:
      maxFileSize: 200Mb
      maxRequestSize: 200Mb

  main:
    banner-mode: "off"

  mvc:
    throw-exception-if-no-handler-found: true

mybatis:
  mapperLocations: classpath:/mapper/*.xml
  typeAliasesPackage: com.uic.webbasederp.domain.po

